-- Script descontinuado neste momento.
--
-- Arquitetura atual do MVP:
-- - acesso via Supabase Data API no backend Streamlit
-- - sem políticas RLS aplicadas por este projeto
--
-- Mantido apenas para referência histórica.
